spring:
  application:
    name: buddy-auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/buddy_auth_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8083
server:
  address: 0.0.0.0
  port: 8083

jwt:
  key:
    key-store: file:D:/travel-app-workspace/keystore/jwt.p12
    key-store-password: Arindam2*
    key-alias: jwtkey                  
    key-password: Arindam2*             
    key-store-type: PKCS12
treecare:
  issuer: http://localhost:8083
  tokens:
    acess-ttl-minutes: 5
    refresh-ttl-minutes: 60
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG